-- ===================================================
-- DEPRECATED — do not use for new imports
-- ===================================================
-- Shared public.sequence_generator was removed. Application tables use per-table
-- {table}_id_seq sequences. Run instead:
--
--   1. database/sync_all_table_sequences.sql     (application domain tables)
--   2. database/migrations/sync_spring_batch_sequences.sql  (Spring Batch only)
-- ===================================================
